"""Initial migration

Revision ID: 1e6f696432ba
Revises: 80c87fd16399
Create Date: 2025-05-11 20:03:03.879879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e6f696432ba'
down_revision = '80c87fd16399'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###