"""Initial migration

Revision ID: 80c87fd16399
Revises: 25f4195e17b7
Create Date: 2025-05-11 19:55:31.284073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80c87fd16399'
down_revision = '25f4195e17b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###