"""Initial migration

Revision ID: c5da25cbd901
Revises: da0269416868
Create Date: 2025-05-11 20:44:02.207178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5da25cbd901'
down_revision = 'da0269416868'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###