"""Initial migration

Revision ID: da0269416868
Revises: 1e6f696432ba
Create Date: 2025-05-11 20:24:01.411263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da0269416868'
down_revision = '1e6f696432ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###